#!/bin/bash
#
# Launcher for memprof parser.

LUA_PATH="/home/shishqa/dev/__tarantool/luajit/tools/?.lua;;" \
	/home/shishqa/dev/__tarantool/luajit/src/luajit /home/shishqa/dev/__tarantool/luajit/tools/sysprof.lua $@
