#!/bin/bash
#
# Launcher for memprof parser.

LUA_PATH="/mnt/WorkDisk/share/dev/__tarantool/luajit/tools/?.lua;;" \
	/mnt/WorkDisk/share/dev/__tarantool/luajit/src/luajit /mnt/WorkDisk/share/dev/__tarantool/luajit/tools/sysprof.lua $@
